CREATE TABLE code_table 
(
   CODE_TABLE_ID        BIGINT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   TABLE_LONG_NAME      VARCHAR (128) NOT NULL,
   COLUMN_LONG_NAME     CHAR (30) NOT NULL,
   DESCRIPTION          VARCHAR (512),
   BUSINESS_FILTER		VARCHAR (10),
   DISPLAY_NAME			VARCHAR (30),
   BPA_AUDIT_TRAIL_ID   BIGINT(8),
   AUDIT_USER           VARCHAR (40) NOT NULL,
   AUDIT_LDAP_DN        VARCHAR (200),
   AUDIT_TIMESTAMP      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX XAK02CODE_TABLE1
  ON code_table
    ( TABLE_LONG_NAME ASC, COLUMN_LONG_NAME ASC );

CREATE INDEX XIE02CODE_TABLE01
  ON code_table
    ( BPA_AUDIT_TRAIL_ID ASC );